server:
  port: 8080

spring:
  application:
    name: nehemiah-building-payment
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  data:
    mongodb:
      uri: mongodb+srv://kelennafavour:YOUR_PASSWORD@nehemiahbuilders.aefet2x.mongodb.net/nehemiah_builders?appName=nehemiahBuilders

app:
  default-created-by: Diana

logging:
  level:
    root: INFO
    com.example.payment: DEBUG